# Generated by Django 5.2.1 on 2025-06-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
